apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: wordpress-htdocs
  name: wordpress-htdocs
spec:
  storageClassName: managed-nfs-storage-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
