apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wordpress-db
  name: wordpress-db
spec:
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: wordpress-db
status:
  loadBalancer: {}
