apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f stack.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress-db
  name: wordpress-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD_FILE
          value: /run/secrets/db-passwords/db-password.txt
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /run/secrets/db-passwords/db-root-password.txt
        - name: MYSQL_USER
          value: wordpress
        image: biarms/mysql:5.5
        name: wordpress-db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
        - mountPath: "/run/secrets/db-passwords"
          name: db-passwords
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      - name: db-passwords
        secret:
          secretName: db-passwords
status: {}
