apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wordpress-phpmyadmin
  name: wordpress-phpmyadmin
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    io.kompose.service: wordpress-phpmyadmin
status:
  loadBalancer: {}
