kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    io.kompose.service: wordpress-phpmyadmin
  name: wordpress-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress-phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress-phpmyadmin
    spec:
      containers:
        - name: wordpress-phpmyadmin
          image: biarms/phpmyadmin:4.8.3
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: wordpress-db
            - name: PMA_PORT
              value: "3306"
          resources:
            requests:
              memory: "32M"
              cpu: "0.2"
            limits:
              memory: "64M"
              cpu: "0.5"
      restartPolicy: Always

