kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    io.kompose.service: gogs-db-admin
  name: gogs-db-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gogs-db-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: gogs-db-admin
    spec:
      containers:
      - image: biarms/pgadmin4:2.1 #biarms/pgadmin4:linux-arm64v8-3.6-beta-48
        name: gogs-db-admin
        ports:
        - containerPort: 5050
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: dummy@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: changeit
        resources: {}
        volumeMounts:
        - mountPath: /pgadmin
          name: gogs-pgadmin-data
      restartPolicy: Always
      volumes:
      - name: gogs-pgadmin-data
        persistentVolumeClaim:
          claimName: gogs-pgadmin-data
status: {}
