version: '3.8'

services:
  wordpress-db:
    image: ${DOCKER_REGISTRY}biarms/mysql:5.7.30
    volumes:
      - wordpress-db-data:/var/lib/mysql
    # ports:
    #   - 31306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wordpress-db-root-password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress-db-password
    secrets:
      - wordpress-db-root-password
      - wordpress-db-password
    deploy:
      replicas: 1
    # NOK: "mem_limit: Set resource limits using deploy.resources" error...
    #mem_reservation: 256m
    #mem_limit: 512m

  wordpress-fpm:
    image: biarms/wordpress:5.4.1-php7.3-fpm-alpine
    volumes:
      - wordpress-htdocs:/var/www/html
    # ports:
    #   - 31900:9000
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress-db-password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - wordpress-db-password
    deploy:
      replicas: 1
    #mem_reservation: 256m #64m
    #mem_limit: 512m #128m

  wordpress-ngnix:
    image: nginx:1.18.0-alpine # See https://hub.docker.com/_/nginx?tab=description
    volumes:
      - ./nginx-conf.d/:/etc/nginx/conf.d/
      - wordpress-htdocs:/var/www/html:ro
    ports:
      - 31080:80
    deploy:
      replicas: 1
    #mem_reservation: 16m
    #mem_limit: 24m

  wordpress-phpmyadmin:
    # container_name: wordpress-phpmyadmin
    image: ${DOCKER_REGISTRY}biarms/phpmyadmin:5.0.2
    ports:
      - 31090:80
    environment:
      - PMA_HOST=wordpress-db
      - PMA_PORT=3306
    deploy:
      replicas: 0
    # mem_reservation: 32m
    # mem_limit: 64m
   # https://hub.docker.com/r/arm32v6/adminer/

volumes:
  wordpress-db-data:
  wordpress-htdocs:

# Inspired by https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
secrets:
  wordpress-db-password:
    file: db-password.txt
  wordpress-db-root-password:
    file: db-root-password.txt
