version: '3.8'

services:
  wordpress-db:
    # container_name: wordpress-db
    image: ${DOCKER_REGISTRY}biarms/mysql:5.7 #.60-linux-arm32v6 #5.5 is for backward compatibility with RPI1 (arm32v6). 5.7 is maybe better for RPI2 or RPI3 (arm32v7)
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-root-password
      - db-password
    deploy:
      replicas: 1
    # NOK: "mem_limit: Set resource limits using deploy.resources" error...
    #mem_reservation: 256m
    #mem_limit: 512m

  wordpress-fpm:
    # container_name: wordpress-fpm
    image: biarms/wordpress:5.4.1-php7.3-fpm-alpine
    volumes:
      - htdocs:/var/www/html
    ports:
      - 9000
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db-password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - db-password
    deploy:
      replicas: 1
    #mem_reservation: 256m #64m
    #mem_limit: 512m #128m

  wordpress-ngnix:
    # container_name: wordpress-ngnix
    image: nginx
    volumes:
      - ./nginx-conf.d/:/etc/nginx/conf.d/
      - htdocs:/var/www/html:ro
    ports:
      - 30080:80
    deploy:
      replicas: 1
    #mem_reservation: 16m
    #mem_limit: 24m

  wordpress-phpmyadmin:
    # container_name: wordpress-phpmyadmin
    image: ${DOCKER_REGISTRY}biarms/phpmyadmin:4.7.7
    ports:
      - 30090:80
    environment:
      - PMA_HOST=wordpress-db
      - PMA_PORT=3306
    deploy:
      replicas: 1
    # mem_reservation: 32m
    # mem_limit: 64m
   # https://hub.docker.com/r/arm32v6/adminer/

volumes:
  db-data:
  htdocs:

# Inspired by https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
secrets:
  db-password:
    file: db-password.txt
  db-root-password:
    file: db-root-password.txt

# Next steps: create a cluster (see https://severalnines.com/blog/mysql-docker-introduction-docker-swarm-mode-and-multi-host-networking)
