version: '3.8'

services:
  gogs-app:
    image: ${DOCKER_REGISTRY}biarms/gogs:0.11.91
    volumes:
     - gogs-data:/data
    # - /etc/timezone:/etc/timezone:ro
    # - /etc/localtime:/etc/localtime:ro
    ports:
     - 32022:22
     - 32080:3000
    deploy:
      replicas: 1

  gogs-db:
    image: ${DOCKER_REGISTRY}postgres:12.3-alpine
    environment:
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD_FILE: /run/secrets/gogs-db-password
      POSTGRES_DB: gogs
    volumes:
     - gogs-db-data:/var/lib/postgresql/data
    # ports:
    #  - 32432:5432
    secrets:
     - gogs-db-password
    deploy:
      replicas: 1
    depends_on:
      - gogs-db

  gogs-db-admin:
    image: ${DOCKER_REGISTRY}biarms/pgadmin4:2.1
    volumes:
     - gogs-db-admin-data:/pgadmin
    ports:
     - 32090:5050
    deploy:
      replicas: 0

volumes:
  gogs-data:
  gogs-db-data:
  gogs-db-admin-data:

secrets:
  gogs-db-password:
    file: db-password.txt